from global_trend_jp_publisher.config import Settings
from global_trend_jp_publisher.models import TrendItem
from global_trend_jp_publisher.pipeline import build_drafts
from global_trend_jp_publisher.processors.categorize import determine_category
from global_trend_jp_publisher.processors.grok_summarizer import GrokSummarizerError, GrokSummary


def test_determine_category_from_source_name() -> None:
    assert determine_category("The Verge", "new device", "AI features", "https://example.com/gadgets/1") == "tech"
    assert determine_category("WSJ.com: Markets", "stocks lower", "gold declines", "https://example.com/markets/1") == "finance"


def test_determine_category_uses_url_and_weighted_terms() -> None:
    assert determine_category(
        "Example Source",
        "Developers get new AI API tools",
        "software teams can automate workflows",
        "https://example.com/tech/api-tools",
    ) == "tech"
    assert determine_category(
        "Example Source",
        "Treasury yield rises as stock market falls",
        "earnings and fed concerns pressure investors",
        "https://example.com/business/markets-update",
    ) == "finance"


def test_build_drafts_applies_category_filter_and_takeaways() -> None:
    items = [
        TrendItem(
            source_name="The Verge",
            category="tech",
            title="AI app update",
            url="https://example.com/tech",
            snippet="A new AI model improves work automation.",
        ),
        TrendItem(
            source_name="WSJ.com: Markets",
            category="finance",
            title="Gold and stocks move lower",
            url="https://example.com/finance",
            snippet="Markets fell after rate concerns.",
        ),
    ]

    drafts = build_drafts(items, category_filter="finance")

    assert len(drafts) == 1
    assert drafts[0].category == "finance"
    assert len(drafts[0].takeaways_ja) == 2
    assert "日本向けの示唆:" in drafts[0].redbook_post


def test_build_drafts_summaries_are_condensed_to_about_400_chars() -> None:
    long_snippet = "This is a detailed sentence about the announcement. " * 40
    items = [
        TrendItem(
            source_name="The Verge",
            category="tech",
            title="Company ships a major update",
            url="https://example.com/tech-update",
            snippet=long_snippet,
        ),
    ]

    drafts = build_drafts(items, settings=Settings(xai_api_key=""))

    assert len(drafts) == 1
    assert len(drafts[0].summary_ja) <= 410
    assert len(drafts[0].summary_en) <= 410
    assert drafts[0].summary_en
    assert drafts[0].security_alert is False


def test_build_drafts_flags_security_alert_from_subcategory_without_grok() -> None:
    items = [
        TrendItem(
            source_name="TechCrunch",
            category="tech",
            title="Critical zero-day vulnerability found in widely used library",
            url="https://example.com/security-breach",
            snippet="A ransomware group is exploiting the flaw to breach corporate networks.",
        ),
    ]

    drafts = build_drafts(items, settings=Settings(xai_api_key=""))

    assert len(drafts) == 1
    assert drafts[0].subcategory == "Security"
    assert drafts[0].security_alert is True
    assert drafts[0].security_reason


def test_build_drafts_uses_grok_summary_when_configured(monkeypatch) -> None:
    grok_summary_ja = "Grokがこの記事を読み込んで生成した日本語要約サンプルです。"
    grok_summary_en = "This is a sample English summary generated by Grok from the article."

    def fake_summarize(title, body, api_key, model):
        assert api_key == "test-key"
        return GrokSummary(
            summary_ja=grok_summary_ja,
            summary_en=grok_summary_en,
            security_important=True,
            security_reason="重大な脆弱性のため。",
        )

    monkeypatch.setattr("global_trend_jp_publisher.pipeline.summarize_with_grok", fake_summarize)

    items = [
        TrendItem(
            source_name="The Verge",
            category="tech",
            title="Company ships a major update",
            url="https://example.com/tech-update",
            snippet="Some announcement details.",
        ),
    ]

    drafts = build_drafts(items, settings=Settings(xai_api_key="test-key"))

    assert len(drafts) == 1
    assert drafts[0].summary_ja == grok_summary_ja
    assert drafts[0].summary_en == grok_summary_en
    assert drafts[0].security_alert is True
    assert drafts[0].security_reason == "重大な脆弱性のため。"


def test_build_drafts_falls_back_when_grok_raises(monkeypatch) -> None:
    def fake_summarize(title, body, api_key, model):
        raise GrokSummarizerError("boom")

    monkeypatch.setattr("global_trend_jp_publisher.pipeline.summarize_with_grok", fake_summarize)

    items = [
        TrendItem(
            source_name="The Verge",
            category="tech",
            title="Company ships a major update",
            url="https://example.com/tech-update",
            snippet="Some announcement details that are long enough to stand alone.",
        ),
    ]

    drafts = build_drafts(items, settings=Settings(xai_api_key="test-key"))

    assert len(drafts) == 1
    assert drafts[0].summary_ja
    assert drafts[0].summary_en